sudo: false
language: node_js
env:
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-msexcel
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-database
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-email
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-ftp
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-soap
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-control-flow
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-selenium-webdriver
- CXX="g++-4.8" NODE_FOLDER=packages/opal-node-pdfreader
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
#- '9'
- '8'
#- '6'
script: npm install && gulp
before_install: cd $NODE_FOLDER
notifications:
  hipchat:
    rooms:
      secure: l9Lh05dEiTUAudKRIfcHL9lY/oDwNsCWf3o1CP3G5nuhuNI+rW2Fl8bWTINFEtF8wqwPNAzb2Zeyl/C3gLEirps+Wk7DXX8MC1+VPZMuOWM69+JnpTv2rtdKFRbRgKG6inY3U+t/uG4JODd6W38yoGWeHddtXmbZ/NZ+cu/HA+ced2z9jGSps5B14AmoVuQF2r5G2pWkSKprhTxnBua4+Up8rP1hQ+3Y7+g+3B7ABn+CQboghJ4sIqtzi4/OsVT+38RaiXXjXPvtglVb88NaJKF0JeoVHEVhBCYipdrL7gjpfyi8DsFYtm8mqJLzq8JL6E/Jcj/tMcDnZPKvlKidv/tYP3C9q5RRSDmFd/otRDBaslw7idPaibL4ac9UhRnjgDPl640iRASGQkyYblAuZzMjrMHtEVUMW6zxipXKSCy/Ae36Go8kN0PJXL+CP3sS/O1A5MiWXhzGsB8u3SsnITwaMj9MR0bbmXfZVPmOW/L1Oo20aiQDlxC9xxn60ojxV9RkDbJJF0yD0RXElFuxT9JpNZ6lJdC4ctTFaLxfiXltkJ+C5BlFt9fZv1NhTaE6FuR2vzCVZqx/6alNjKzGjabLMPLINi6bnHoV/tM11iqj0iygDokvum903wjseQDETtaD0K0pbjgUKaeVebHCGLgCGU1AsdEdx/L83/OH2aI=
  slack:
    secure: GbckymyJhtAdXxEY5IiCGdoY1ixGizZhfxhOvs7JaossPOkbtzzDvU3oyY08BHLkKri0/DMjb/PEudNbTYlQ/hTkivbVMuL/av99L2tnd8LN8N75vAt06M++IT2yaEHWgiI+abZjN4c5csfG2lm42wa2rgigXBIKK0fy5UfootiUnJUXOyHl1g54sL9kaNSmMylgfYUF5Hhzk7YUE/q8uzP3/MhKrDGYVs2YEynfHNOmhFX1OIdERYLh6NvYOeeDwowWalBXpZDH4xQeqBQSLCxe+GspnRXE8wIDq5JIvbQ0noOVBoRghM7g8rcrZ1e5kzq4YgpGT5EU++XfrNOYrGCzwfgdBJN+UQYYii0IrqPv6KCglyXMv8ZHIkW8GJ8/vhQlesrIUY69mrW/GKap+0WbnpO5x7ScefcQFNsaedt0M9GTMn5zoN7CXIR+LfWe91NyeEhqfL3wIeMdZ8tUvh3zurBbZTm6717KyQczFUPZgNhUtfuTVnjkoboXU1/UqY/PxyR+cABS2GqJ2oxQfqaYjl6jiYd0JRd6hZyllmLE3ZNWs3yRQQoq63uxWg+XzYrmK96WFZpmbwFoYUFxS69W+jHsuPVwYKgSlcLw90Dd4G/1BVfR/LLCfW6Jw4nEW4M4swEz3z5G60xEKUiyhdWavk/q3ZkXPUYNj6JXZco=
