sudo: false
language: node_js
env:
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-msexcel
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-database
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-email
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-ftp
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-soap
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-control-flow
- CXX="g++-4.8" NODE_FOLDER=packages/orpa-node-selenium-webdriver
- CXX="g++-4.8" NODE_FOLDER=packages/opal-node-pdfreader
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
#- '9'
- '8'
#- '6'
script: npm install && gulp
before_install: cd $NODE_FOLDER
notifications:
  hipchat:
    rooms:
      secure: FldaNzv+uB2a+5yyxWIRdZG8z+L10ixq6OiyTGEU6iK5UN/R6nRrVNepdEOyuObpCfVpe+iw8HNaY4Qkejv5ES3Hv9xuzpZC59wMttQYWMJZtBnKw3zSZrKxBs944mWcnviO9FONORYBePCq8f0JhBkThNJvdXtvT2UsO3DFVTXRB/2hg3NMWJO9x7Nev1mFJgtdM3yEnBxs5d+oSYrtFURTXi1aDYlujwYJWDUT5z7vjYCIGhI30IrIrR+E4kpKS0Sji1ldMHffPk7mlLWCbA81ipif/G1fmsaqIIF8/LEgFPtTmplmm9OlBhCb/k4zwanFIX+sVATljoeZqX+Ds5hmfkwB3k+uUDO/BtC0pucZ7OxM79OzI9Njapw7yE+H1p5ryq9byGHlK7Ogb37ZQIXu3XjbmNOXeZfzvRgzueeBHOXKN4BTJxYg/BfAV+hULpv/U4tw0bC/FApplG9XrM2SWIX2PlroHBNXP8F4ijP+4fB6cuD0YIpKXhrW84VJAb6SWlnu/quQPJA2fKJ5vr+dsFK6vwKkXe3c0kSfw5bURbmgJlhTg102GyEOzYNUL/NMXyQdCqu5o6/Lq8ED0SNtVqBRfCCQRAyikszcyq6CAsYmBuCeTnKIhzGwZEw+4AByG9N+X+BOlr1wes6Psxaeknk6q3WQRn0MvyWk/ec=
  slack:
    secure: QUHUvnT/UzDC2O+yrPotkCySuRzNbaTyl5aJl4VIOWsA2aGaJHoARCaD6rosZOMGD5al/tgAvV4ZB1Aa4jFkn8TR8IXDoe97XMLgP9aBygUW63V87O7P5qpHyAXUD5F9PxnPHx/Fz/kuLfkgHxYF3H4GyfwY7KVjR47HhfmMBupY9aN/LxKiyFuzMIhmLXc/b2VsiC5ih9B+7etU6NW8zPz90Y+YYPQ8eMRXZZ4wnTuRd4zWRaBP4eyvM6wRkUOJTF7dltEeFgmcrvflGnIm22sFboByr1OjY4tnPeAAZB1DUJHvwweXIQhK23kscrV73VQ4CMvxbOdWc5UGDIx1xurfYkYmT1Dt3MtUUZXKl/Jd0A1hHEWHSiVO84jUkYkJU3tS8REaFdaqi9Noyr5R3qqa7DJS/vadCH2Jn2rF8fLjBtzr9VIG2bn8nwgUm1a+agTyV37wyQv3ydfwjyMEMQ6FEdcRvJSv0oJAlJczhDsPOsP2py/Vokb5dM11WUEUYFqI5AQ82l20bcHpE4H2LJ2XwXbTg8N+tKBchugqrXPNdvGoz2/8qp0kVdMxZcjnNfU5g7KnHdwou/sVFJ3lyDDU5v905IpjN5D5c1LQK7pCbS7EdvtlCjKQKLQwgVCxnjqQ+3+yijrnJcPif+Fghw0Mgkdd4py3wnP6HmhDn/0=
